development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: inbook_development
  pool: 5
  username: root
  password: letmein
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: inbook_test
  pool: 5
  username: root
  password: letmein

